services:
  app:
    build: .
    container_name: lsi-strategie-app
    ports:
      - "3005:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  node_modules:
