// next-themesを使用して、テーマの切り替えを行うためのレイアウトコンポーネント。
// attribute="class" は、テーマをCSSクラスで切り替える設定。

import { ThemeProvider } from 'next-themes';
import './globals.css';   // グローバルCSSファイルがあれば

export const metadata = {
  title: 'Your App Title',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider 
          attribute="class"
          defaultTheme="system"
          enableSystem={true}
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}